print("Name : Sujan")
print("From : Pokhara Nepal")
print("Class : Pyhton")
print("Day : 1")
print("Assignment : 1")
print("Instructor : Bishwo Raj Poudel")
print("Institute : Technology Channel")
print("Duration : 1.5 months")
print("Start Date : Ashad 3")
print("End Date : Shrawan 15")
print("Har Har Mahadev \nShiva Bhagawan")
print("Name \t Sujan")
print('"Sujan"')
print("\"sujan\"")
print(" I \"Love\" pytho \"class\" everyday")
print("'I' \"love\" python")
# I lo ve